### ISSUE TITLE
Improvement: Maybe add cache to travis again

### ISSUE THREAD

**Issue by L4B0MB4** [sprinteins/ghost#65]
Think about adding this back to the travis.yaml

```
cache:
  yarn: true
  directories:
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
    - $HOME/.npm/_prebuilds

before_cache:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then rm -rf $HOME/.cache/electron-builder/wine; fi
```
